# Generated by Django 4.1.5 on 2023-02-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
