# Generated by Django 4.1.7 on 2023-02-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Cart', models.CharField(max_length=25)),
                ('Price_Cart', models.IntegerField(default=0)),
                ('Image_Cart', models.ImageField(upload_to='ecom/images')),
                ('Category_Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.category')),
            ],
        ),
    ]
