# Generated by Django 4.1.7 on 2023-02-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Price_Cart',
            field=models.IntegerField(),
        ),
    ]
