# Generated by Django 4.1.5 on 2023-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='User',
            field=models.CharField(max_length=150),
        ),
    ]
