# Generated by Django 4.1.5 on 2023-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_remove_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
