# Generated by Django 4.1.7 on 2023-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prod_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
