# Generated by Django 4.1.7 on 2023-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_cart_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
