# Generated by Django 4.1.5 on 2023-03-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
