# Generated by Django 4.1.5 on 2023-03-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
