# Generated by Django 4.1.5 on 2023-04-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Card_Cvv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Card_Expiration',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Card_Nummber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Payment_Method',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
