# Generated by Django 4.1.5 on 2023-04-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_cart_card_cvv_cart_card_expiration_cart_card_nummber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Card_Cvv',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Card_Expiration',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Card_Nummber',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Payment_Method',
        ),
        migrations.AddField(
            model_name='order',
            name='Card_Cvv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Card_Expiration',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Card_Nummber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Payment_Method',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
